"""
excel_grapher: Build and analyze dependency graphs from Excel workbooks; evaluate formulas; export standalone Python.

Public API is namespaced by role: excel_grapher.grapher, excel_grapher.evaluator, excel_grapher.exporter.
Convenience re-exports below keep existing call patterns working.
"""

from .evaluator import (
    CellValue,
    ExcelRange,
    FormulaEvaluator,
    ParseError,
    XlError,
)
from .grapher import (
    And,
    Compare,
    CycleError,
    CycleReport,
    DependencyGraph,
    DynamicRefConfig,
    DynamicRefError,
    DynamicRefLimits,
    GuardCellRef,
    GuardExpr,
    Literal,
    Node,
    NodeHook,
    NodeKey,
    Not,
    Or,
    ValidationResult,
    ValueType,
    WorkbookCalcSettings,
    create_dependency_graph,
    format_cell_key,
    format_key,
    get_calc_settings,
    needs_quoting,
    to_graphviz,
    to_mermaid,
    to_networkx,
    validate_graph,
)

__all__ = [
    "And",
    "GuardCellRef",
    "Compare",
    "CycleError",
    "CycleReport",
    "DependencyGraph",
    "DynamicRefConfig",
    "DynamicRefError",
    "DynamicRefLimits",
    "Literal",
    "Node",
    "NodeKey",
    "Not",
    "NodeHook",
    "Or",
    "GuardExpr",
    "ValidationResult",
    "ValueType",
    "WorkbookCalcSettings",
    "create_dependency_graph",
    "format_cell_key",
    "format_key",
    "get_calc_settings",
    "needs_quoting",
    "to_graphviz",
    "to_mermaid",
    "to_networkx",
    "validate_graph",
    "CellValue",
    "ExcelRange",
    "FormulaEvaluator",
    "ParseError",
    "XlError",
]
