"""Series binding manifest: load, validate, and canonicalize workbook series specs."""

from __future__ import annotations

from excel_grapher.series_bindings.audit import (
    DIRECTIONS,
    AuditFinding,
    BindingResolutionAuditReport,
    audit_binding_resolutions,
    find_duplicate_formula_cell_bindings,
    find_duplicate_internal_formula_cell_bindings,
    find_sparse_label_bind_issues,
    findings_from_resolution,
    format_audit_findings,
    unfilled_label_binds,
)
from excel_grapher.series_bindings.burndown import (
    BindingBurndownReport,
    collapse_unbound_cells_to_ranges,
    contiguous_column_ranges,
    find_unbound_internal_formula_cells,
    format_burndown_report,
    format_row_column_spans,
    group_unbound_cells_by_sheet_row,
    internal_binding_burndown,
    layout_hint_for_range,
    layout_hint_for_span,
    load_exempt_addresses,
    manifest_binding_addresses,
    required_internal_formula_cells,
)
from excel_grapher.series_bindings.canonical import bindings_canonical_sha256
from excel_grapher.series_bindings.constant_series import derive_constant_series
from excel_grapher.series_bindings.domains import (
    SeriesDomainHandle,
    SeriesDomainIndex,
    SeriesRelationError,
    cell_type_env_from_bindings,
    undomained_leaves,
)
from excel_grapher.series_bindings.groups import (
    GroupMember,
    GroupNode,
    GroupsManifest,
    bindings_export_order,
    bindings_have_groups,
    group_manifest,
    group_slug,
)
from excel_grapher.series_bindings.input_coerce import Layout, SeriesInput, coerce_setter_input
from excel_grapher.series_bindings.input_series import derive_input_series
from excel_grapher.series_bindings.internal_series import derive_internal_series
from excel_grapher.series_bindings.load import (
    SeriesBindingsLoadError,
    load_series_bindings,
    merge_series_binding_documents,
    parse_bindings_file,
)
from excel_grapher.series_bindings.normalize import (
    has_constant_direction,
    has_input_direction,
    has_internal_direction,
    has_output_direction,
    is_cataloged_series,
    merge_series_entries,
    normalize_bindings_document,
    normalize_series_entry,
)
from excel_grapher.series_bindings.output_series import derive_output_series
from excel_grapher.series_bindings.ranges import (
    expand_data_range,
    expand_data_range_for_graph,
    series_data_ranges,
)
from excel_grapher.series_bindings.resolve import (
    bound_label_addresses,
    resolve_series_binding,
    resolve_series_bindings,
)
from excel_grapher.series_bindings.schema import (
    SeriesBindingsSchemaError,
    format_schema_errors,
    validate_bindings_document,
)
from excel_grapher.series_bindings.types import (
    ConstantSeries,
    ConstantSeriesCell,
    InputSeries,
    InputSeriesCell,
    InternalSeries,
    InternalSeriesCell,
    LeafResolution,
    OutputSeries,
    OutputSeriesCell,
    Record,
    Records,
    ResolutionIssue,
    ResolutionReport,
    Scalar,
    SeriesResolution,
    ValidationIssue,
    ValidationLevel,
    ValidationReport,
    WorkbookSeriesBindings,
)
from excel_grapher.series_bindings.upsert import (
    SHARD_FILENAMES,
    BindingUpsertError,
    BindingUpsertResult,
    bootstrap_binding_shards,
    upsert_series_binding,
)
from excel_grapher.series_bindings.validate import validate_series_bindings
from excel_grapher.series_bindings.versions import (
    CURRENT_SCHEMA_VERSION,
    IMPLEMENTED_BIND_KINDS,
    IMPLEMENTED_LAYOUTS,
    SUPPORTED_SCHEMA_VERSIONS,
    is_bind_implemented,
    is_layout_implemented,
)
from excel_grapher.series_bindings.workflow import (
    BindingsCheckResult,
    run_binding_checks,
    series_binding_public_addresses,
    validate_bindings_workbook,
)

__all__ = [
    "ConstantSeries",
    "ConstantSeriesCell",
    "InputSeries",
    "InputSeriesCell",
    "InternalSeries",
    "InternalSeriesCell",
    "OutputSeries",
    "OutputSeriesCell",
    "Record",
    "Records",
    "AuditFinding",
    "BindingBurndownReport",
    "BindingResolutionAuditReport",
    "BindingUpsertError",
    "BindingUpsertResult",
    "CURRENT_SCHEMA_VERSION",
    "DIRECTIONS",
    "IMPLEMENTED_BIND_KINDS",
    "IMPLEMENTED_LAYOUTS",
    "SHARD_FILENAMES",
    "SUPPORTED_SCHEMA_VERSIONS",
    "LeafResolution",
    "ResolutionIssue",
    "ResolutionReport",
    "Scalar",
    "SeriesResolution",
    "SeriesBindingsLoadError",
    "SeriesBindingsSchemaError",
    "SeriesRelationError",
    "SeriesDomainHandle",
    "SeriesDomainIndex",
    "ValidationIssue",
    "ValidationLevel",
    "ValidationReport",
    "WorkbookSeriesBindings",
    "BindingsCheckResult",
    "GroupMember",
    "GroupNode",
    "GroupsManifest",
    "bound_label_addresses",
    "bindings_canonical_sha256",
    "cell_type_env_from_bindings",
    "undomained_leaves",
    "bindings_export_order",
    "bindings_have_groups",
    "group_manifest",
    "group_slug",
    "Layout",
    "SeriesInput",
    "coerce_setter_input",
    "derive_constant_series",
    "derive_input_series",
    "derive_internal_series",
    "derive_output_series",
    "has_constant_direction",
    "has_input_direction",
    "has_internal_direction",
    "has_output_direction",
    "is_cataloged_series",
    "merge_series_entries",
    "normalize_bindings_document",
    "normalize_series_entry",
    "expand_data_range",
    "expand_data_range_for_graph",
    "series_data_ranges",
    "format_schema_errors",
    "load_series_bindings",
    "merge_series_binding_documents",
    "parse_bindings_file",
    "resolve_series_binding",
    "resolve_series_bindings",
    "run_binding_checks",
    "series_binding_public_addresses",
    "validate_bindings_document",
    "validate_bindings_workbook",
    "validate_series_bindings",
    "audit_binding_resolutions",
    "bootstrap_binding_shards",
    "collapse_unbound_cells_to_ranges",
    "contiguous_column_ranges",
    "find_duplicate_formula_cell_bindings",
    "find_duplicate_internal_formula_cell_bindings",
    "find_sparse_label_bind_issues",
    "find_unbound_internal_formula_cells",
    "findings_from_resolution",
    "format_audit_findings",
    "format_burndown_report",
    "format_row_column_spans",
    "group_unbound_cells_by_sheet_row",
    "internal_binding_burndown",
    "layout_hint_for_range",
    "layout_hint_for_span",
    "load_exempt_addresses",
    "manifest_binding_addresses",
    "required_internal_formula_cells",
    "unfilled_label_binds",
    "upsert_series_binding",
    "is_bind_implemented",
    "is_layout_implemented",
]
